import { Outfit } from 'next/font/google';
import './globals.css';
import Navbar from '../../components/ui/Navbar';
import { ChakraProvider } from '@chakra-ui/react'; 

const outfit = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: 'Pomo',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} flex`}>
        <ChakraProvider>
          <Navbar /> 
          <main className="flex-1 ml-64"> 
            {children}
          </main>
        </ChakraProvider>
      </body>
    </html>
  );
}
