import { Outfit } from 'next/font/google';
import './globals.css';
import Navbar from '../../components/ui/Navbar';


const outfit = Outfit({ subsets: ['latin'] });

export const metadata = {
  title: 'Pomo',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} flex`}>
        <Navbar />
        <main className="flex-1"> {/* Ajusta ml-64 según el ancho de tu Navbar */}
          {children}
        </main>
      </body>
    </html>
  );
}
